import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import { Banner } from "@/components/Banner";
import { About } from "@/components/About";
import Skills from "@/components/Skills";
import Project from "@/components/Project";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Education from "@/components/Education";
import { FaArrowUp } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mahfuja Ahasan Muna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.ibb.co/FwK884F/logo.png" />
      </Head>
      <main className="w-full h-screen bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll font-bodyFont scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
        <Navbar></Navbar>
        <div className="w-full h-[88vh] mx-auto xl:flex items-center gap-20 justify-center">
          <div className="w-full h-[88vh] mx-auto p-4 relative">
            {" "}
            <Banner />
            <About />
            <Skills />
            <Project />
            <Education />
            <Contact />
            <Footer></Footer>
            <a
              className="hover:animate-bounce text-textBlue border-2 border-textBlue p-2 fixed bottom-0 right-0 mb-8 mr-8"
              href="#home"
            >
              <FaArrowUp />
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
